---
development:
  cloud_name: ducndpba6
  api_key: "483724467538947"
  api_secret: Eh9tXSTchicMtGSYhzpRyfHR8NM
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ducndpba6
  api_key: "483724467538947"
  api_secret: Eh9tXSTchicMtGSYhzpRyfHR8NM
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: ducndpba6
  api_key: "483724467538947"
  api_secret: Eh9tXSTchicMtGSYhzpRyfHR8NM
  enhance_image_tag: true
  static_file_support: false
